
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-webhook-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    receivers:
      - name: 'remediation-webhook'
        webhook_configs:
         
          - url: 'http://remediation-service.monitoring.svc.cluster.local:8080/alert'
    route:
      receiver: 'remediation-webhook'
      
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
