
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaoskube
  namespace: chaos-testing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaoskube
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["list", "get", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaoskube
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaoskube
subjects:
  - kind: ServiceAccount
    name: chaoskube
    namespace: chaos-testing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaoskube
  namespace: chaos-testing
  labels:
    app: chaoskube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaoskube
  template:
    metadata:
      labels:
        app: chaoskube
    spec:
      serviceAccountName: chaoskube
      containers:
        - name: chaoskube
          image: quay.io/linki/chaoskube:v0.25.0
          args:
            - --namespaces=default
            - --skip-target-names=chaoskube
            - --interval=5m 
